name: native_virtual_keyboard_example
description: "Demonstrates how to use the native_virtual_keyboard plugin."
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  native_virtual_keyboard:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
