name: native_virtual_keyboard
description: "An almost pixel perfect Flutter replica of iOS and Android native keyboards."
version: 0.2.5
homepage: https://chunkytofustudios.com
repository: https://github.com/ChunkyTofuStudios/native_virtual_keyboard

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  device_info_plus: ^12.3.0
  flutter_svg: ^2.2.3
  logging: ^1.3.0
  material_symbols_icons: ^4.2906.0
  vector_graphics: ^1.1.19

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0

flutter:
  generate: true
  assets:
    - assets/images/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true

# All platforms supported since plugin is Dart only.
platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
